### PR TITLE
rebar3 plugin

### PR DESCRIPTION
**Pull request by lpil**

### CODE REVIEW

**Comment by tsloughter** [comment]
Note that there is a new and far better interface for dealing with code paths and compiler in 3.7.0. We kept the old in there with a deprecated so this will still work, but you'll want to move to the new stuff. Sadly haven't documented it yet... But if you look at the new compile modules, like `rebar_compile_mib`, they are pretty small. And look at the use of the new module `rebar_paths`.

**Comment by lpil** [comment]
Thanks for the tip @tsloughter. Is there a particular example I should be looking at?

**Comment by lpil** [comment]
@tsloughter Could we get the callbacks in the behaviour documented/commented? It's unclear to me what the arguments are returns values are, and the examples don't make use of all of them in an obvious way.

**Comment by tsloughter** [comment]
Yea. I'll get around to that soon, at least next week.

**Comment by lpil** [comment]
Thank you. Has rebar 3.7.0 been released? I've run `rebar3 local upgrade` and I'm still on 3.6.2

**Comment by tsloughter** [comment]
Na, it is still 3.7.0-rc2. Hopefully soon.

**Comment by lpil** [comment]
Thanks again, I'll use master

**Pull request closed without merging**
