### PR TITLE
Release automation

### PR DESCRIPTION
**Pull request by lpil**
Closes https://github.com/lpil/gleam/issues/90

### CODE REVIEW

**Comment by NobbZ** [comment]
Will you also provide prebuilts for MUSL, or only the dockerfile?

**Comment by lpil** [comment]
The prebuild Linux binary in the release page is statically linked against MUSL so should work on any AMD64 Linux distribution :)

**Comment by NobbZ** [comment]
Will you in future always provide the precompiled binary with every tag?

I could probably cut the build times for the AUR package drastically if you guarantee availability of the binary.

**Comment by lpil** [comment]
Yes, from here on out I intend to. In future I'll probably have a build server run these scripts when a new tag is pushed

**Comment by NobbZ** [comment]
Move the project to gitlab and I could help you set it up ;)

But I'm sure it will be possible using circle-ci or travis-ci as well.

**Comment by lpil** [comment]
The limiting factor is mostly macOS and the lack of a build server for it. When Gleam gets bigger I may contact some CI providers such circle to see if they will offer up some free macOS build time.

**Comment by NobbZ** [comment]
Mac OS isn't that important ;)

But yes, I fully understand the considerations… And I assume, the same is true for windows?

**Comment by lpil** [comment]
Lots of people use it, it's plenty important :)

I'd like to provide these for Windows as well but I don't have a Windows computer or any Windows experience, so it's even more difficult.

**Comment by NobbZ** [comment]
I've one available at office… And at least for CI to run tests and to compilation to download the artifact after the fact should be doable. I know there are CI services available that offer CI time on windows for free.

**Comment by lpil** [comment]
Good point! I'm sure we can find what we need somewhere. I'll open an issue to track this.

**Pull request merged**
