### PR TITLE
Create simple GitHub Actions workflow.

### PR DESCRIPTION
**Pull request by EskiMag**
This Pull Request is related to issue #232.

I created a simple GitHub Actions workflow which replicates current Circle CI build process. It doesn't use cache, since that is not available in GitHub Actions yet.

What should be the output of this workflow? Is the successfull run of all the commands good enough enough, or should this workflow produce some artifacts or a GitHub Release?

GitHub Actions supports MacOS runners too, so it is possible to even do a release after a new tag is created in the repository along with the linux and macos binaries. I assume you're doing this manually now. Am I right?

### CODE REVIEW

**Comment by lpil** [comment]
Hi! Thanks for this!

Yes, you're right about the manual release. I would like to make the release process automated later.

How does this know to use an image that has cargo installed?

**Comment by lpil** [comment]
Do you know if there is a way to test this on a branch? I've not managed to figure it out yet!

**Comment by EskiMag** [comment]
Here's a list of what's included in the GitHub virtual environment: https://help.github.com/en/github/automating-your-workflow-with-github-actions/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts

I specified `ubuntu-latest` which at this moment refers to `ubuntu-18.04`. More info is here: https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on

Currently in `ubuntu-latest`, there's:
* rustup (1.19.0)
* rust (1.37.0)
* cargo (1.37.0)
* rustfmt (1.3.0-stable)
* clippy (0.0.212)
* rustdoc (1.37.0)

Now I realize that maybe using a containerized job would be a better idea. That way we can specify  exactly what will be used. More info here: https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontainer
If there's no container specified, the workflow will run on a host directly - this is the currently proposed way, which will be changed I will change in a moment.

I am going to update the wofklow to use the same container as is used by Circle CI at this moment.

I don't know how to test this on a branch yet. I tried to find this information, but with no luck.

**Comment by lpil** [comment]
> I don't know how to test this on a branch yet. I tried to find this information, but with no luck.

I'll try merging this and see how that goes :)

**Comment by EskiMag** [comment]
OK, it went well. https://github.com/lpil/gleam/commit/c1fd94f6dc3b765bc02f34e8c58762ec63a706ee/checks?check_suite_id=275620440

**Comment by EskiMag** [comment]
If you have some proposals on how to improve the whole CI, let me know somehow. :-)

**Comment by lpil** [comment]
Awesome! I'll make some extra tickets in the issue tracker now :)

**Pull request merged**
